In [ ]:
1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?
NumPy (Numerical Python) is a fundamental package in Python for scientific computing. Its primary purpose is to provide support for large, multi-dimensional arrays and matrices, along with a variety of mathematical functions to operate on these arrays. The advantages of using NumPy include:

Performance: NumPy arrays are more efficient than Python lists for numerical operations, as they are implemented in C and use contiguous memory.
Convenience: NumPy provides a wide range of optimized functions for mathematical and statistical computations (e.g., linear algebra, Fourier transforms).
Interoperability: NumPy arrays integrate seamlessly with many other libraries (e.g., pandas, SciPy, Matplotlib).
Vectorization: NumPy allows vectorized operations that eliminate the need for explicit loops, making the code more readable and concise.


2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?
np.mean(): This function computes the arithmetic mean along the specified axis or of the entire array. It treats all elements equally and returns a simple mean.
np.average(): This function is more flexible as it allows for weighted averages using the weights parameter. If no weights are provided, it behaves like np.mean().
When to use one over the other:

Use np.mean() when you want a simple arithmetic mean without any weights.
Use np.average() when the data elements have varying importance, and you want to calculate a weighted average.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.
In NumPy, reversing an array along different axes can be done using slicing or specialized functions. Below are methods for reversing 1D and 2D arrays:

You can reverse a 1D NumPy array using slicing. This technique uses the syntax `[::-1]` to step through the array in reverse.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]  # Reverses the entire array
print(reversed_arr)
```
**Output**:
```
[5 4 3 2 1]
```

For 2D arrays, you can reverse along different axes—rows (vertically) or columns (horizontally).

You can reverse a 2D array along its rows using the slicing method `[::-1]` on the first axis.
```python
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
reversed_rows = arr[::-1]
print(reversed_rows)
```
**Output**:
```
[[7 8 9]
 [4 5 6]
 [1 2 3]]
```

To reverse a 2D array along its columns, you use slicing on the second axis with `[:, ::-1]`.
```python
reversed_columns = arr[:, ::-1]
print(reversed_columns)
```
**Output**:
```
[[3 2 1]
 [6 5 4]
 [9 8 7]]
``

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.
You can determine the data type of elements using the dtype attribute:

arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64

Importance of Data Types:

Memory management: NumPy allows you to specify data types (e.g., int8, float32), helping optimize memory usage based on the precision required.
Performance: Using an appropriate data type for the task can significantly improve performance, as smaller types use less memory and processing power.


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
ndarray (n-dimensional array) is the primary data structure in NumPy for storing arrays of any dimension.
Key features:
Supports multi-dimensional arrays.
Elements are stored in contiguous memory, allowing for fast access and manipulation.
Efficient mathematical operations via vectorization.
Supports broadcasting, enabling operations on arrays of different shapes.
Differences from Python lists:

Efficiency: ndarrays are more memory- and time-efficient than lists.
Fixed type: All elements in an ndarray have the same data type, whereas Python lists can store mixed types.
Multi-dimensional support: Python lists are inherently 1D (though they can be nested for multi-dimensional support), while ndarrays are designed for n-dimensional arrays.


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations ?
Memory efficiency: NumPy arrays store elements in contiguous memory, leading to faster access compared to Python lists, which store references to objects.
Vectorization: NumPy allows vectorized operations that eliminate the need for explicit loops, making the code faster and more concise.
Reduced overhead: NumPy's operations are implemented in low-level languages like C and Fortran, minimizing the overhead of Python's dynamic typing.
Optimized for large-scale operations: When dealing with large datasets, NumPy can handle operations like matrix multiplications and element-wise computations significantly faster than lists.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output?

In NumPy, vstack() and hstack() are used to stack arrays along specific dimensions. Here's a comparison of the two functions:

1. vstack() (Vertical Stacking)
Purpose: Stacks arrays vertically (along rows). This adds arrays as new rows, combining them in the vertical (row-wise) direction.
Array Dimensions: All arrays must have the same number of columns (second dimension).
Example:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
print(result)
Output:

[[1 2 3]
 [4 5 6]]

2 .hstack() (Horizontal Stacking)
Purpose: Stacks arrays horizontally (along columns). This adds arrays as new columns, combining them in the horizontal (column-wise) direction.
Array Dimensions: All arrays must have the same number of rows (first dimension).
Example:
python
Copy code
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
print(result)
Output:
[1 2 3 4 5 6]

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions?
In NumPy, fliplr() and flipud() are methods used to flip arrays along different axes. Here's a detailed explanation of their differences and effects on various array dimensions:

1. fliplr() (Flip Left-Right)
Purpose: Flips an array left to right (i.e., reverses the order of columns).
Effect: For 2D arrays, it reverses the order of elements in each row. For 1D arrays, it is equivalent to reversing the entire array.
Example for 1D Array:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
flipped1d = np.fliplr([arr1d])
print(flipped1d)
Output:
[[5 4 3 2 1]]

2. flipud() (Flip Up-Down)
Purpose: Flips an array up to down (i.e., reverses the order of rows).
Effect: For 2D arrays, it reverses the order of rows. For 1D arrays, it has no effect as there is no second axis to flip.
Example for 1D Array:
python
Copy code
arr1d = np.array([1, 2, 3, 4, 5])
flipped1d = np.flipud([arr1d])
print(flipped1d)
Output:

[[1 2 3 4 5]]

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike split(), which requires the array to be split evenly, array_split() can handle uneven splits by distributing the remaining elements to smaller sub-arrays when the array cannot be divided evenly.

Functionality of array_split()
Parameters:
array: The array to be split.
indices_or_sections: This can be an integer specifying the number of equal-sized sub-arrays, or it can be a list/array specifying the indices where the array should be split.
axis: The axis along which to split the array (default is 0, i.e., row-wise for 2D arrays).
Handling Uneven Splits
When the array cannot be split into equal parts, array_split() ensures that the extra elements are distributed among the first sub-arrays. This means that the first few sub-arrays will have one more element than the others.


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

1. Vectorization
Concept: Vectorization in NumPy refers to the ability to perform operations on entire arrays or matrices without the need for explicit loops. Instead of iterating through elements one by one, NumPy performs operations in a more efficient, optimized manner using low-level implementations.

How it Works:

Underlying Implementation: NumPy operations are implemented in C and Fortran, which are much faster than Python loops due to optimized memory handling and lower-level computations.
Operations on Arrays: When you perform operations on NumPy arrays, they apply element-wise operations efficiently without the need for manual looping.
Benefits:

Performance: Vectorized operations are typically much faster than using Python loops because they utilize efficient, low-level implementations.
Readability: Code is more concise and easier to read, as operations are applied to entire arrays or matrices in a single line.
Optimization: NumPy's internal optimization reduces the overhead of Python's dynamic typing and loop control.

2. Broadcasting
Concept: Broadcasting is a powerful mechanism in NumPy that allows operations between arrays of different shapes. It automatically adjusts the dimensions of the arrays to make their shapes compatible for element-wise operations.

How it Works:

Rules for Broadcasting:
Align Dimensions: Starting from the rightmost dimensions, the dimensions of the arrays are compared. Arrays are aligned by adding dimensions of size 1 where necessary.
Shape Compatibility: Arrays are broadcasted to match each other's shapes if their dimensions are either equal or one of them is 1.
Benefits:

Flexibility: Broadcasting allows for operations between arrays of different shapes, reducing the need to manually reshape or expand arrays.
Efficiency: It avoids the need to create large temporary arrays by performing operations on smaller arrays and broadcasting their results efficiently.


**Practical Question**

In [4]:
import numpy as np
import pandas as pd

#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
array_3x3 = np.random.randint(1, 101, size=(3, 3))
array_3x3

transposed_array = np.transpose(array_3x3)
transposed_array

array_3x3 , transposed_array


(array([[59, 27, 81],
        [18, 20, 26],
        [70,  1, 68]]),
 array([[59, 18, 70],
        [27, 20,  1],
        [81, 26, 68]]))

In [5]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np

array_1d = np.arange(10)
array_1d

array_2x5 = array_1d.reshape(2, 5)
array_2x5

array_1d , array_2x5

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [6]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

array_4x4 = np.random.rand(4, 4)
array_4x4

bordered_array = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
bordered_array

array_4x4 , bordered_array


(array([[0.23482667, 0.48486111, 0.58899206, 0.48402442],
        [0.95174514, 0.924727  , 0.07137365, 0.32155141],
        [0.32043066, 0.74507987, 0.2799497 , 0.5061515 ],
        [0.83582102, 0.60850526, 0.64808985, 0.26722571]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.23482667, 0.48486111, 0.58899206, 0.48402442,
         0.        ],
        [0.        , 0.95174514, 0.924727  , 0.07137365, 0.32155141,
         0.        ],
        [0.        , 0.32043066, 0.74507987, 0.2799497 , 0.5061515 ,
         0.        ],
        [0.        , 0.83582102, 0.60850526, 0.64808985, 0.26722571,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

In [7]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

array_integers = np.arange(10, 61, 5)
array_integers



array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [8]:
#5 .Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.
import numpy as np

array_strings = np.array(['python', 'numpy', 'pandas'])


upper_case = np.char.upper(array_strings)
lower_case = np.char.lower(array_strings)
title_case = np.char.title(array_strings)

print("Uppercase:\n", upper_case)
print("Lowercase:\n", lower_case)
print("Title Case:\n", title_case)


Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Title Case:
 ['Python' 'Numpy' 'Pandas']


In [9]:
#6 .Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

words = np.array(['hello', 'world'])

spaced_words = np.char.join(' ', words)
spaced_words


array(['h e l l o', 'w o r l d'], dtype='<U9')

In [11]:
#7 .Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

identity_matrix = np.eye(5)
identity_matrix

diagonal_elements = np.diag(identity_matrix)
diagonal_elements

identity_matrix , diagonal_elements

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

In [12]:
#8. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [13]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

array_100 = np.random.randint(0, 1001, size=100)
array_100

array([858, 373, 293, 386, 204, 976, 864, 398, 555, 700, 775, 120, 302,
       130, 634, 198,  71,  96, 737, 286, 563, 730, 908, 705, 812, 615,
       609, 205, 765, 293, 497, 995, 710, 465, 705, 644, 182, 133, 757,
       154, 114, 278, 528, 790, 196, 292, 802,  44,  26, 189, 100,  18,
       434, 626, 306, 107,  55, 941, 485, 272, 194,  88, 602, 523, 234,
       434, 131, 927, 957,  61, 254, 501,  23, 165, 106, 437, 964, 973,
       552, 821, 561,  98, 941, 800, 747, 495, 352, 308, 104, 938,  47,
       747, 486, 580, 236, 523,  76, 717, 766, 812])

In [19]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(0, 35, size=30)
print("Daily Temperatures:\n", daily_temperatures)

# Number of days and number of weeks
num_days = len(daily_temperatures)
num_weeks = num_days // 7

# Truncate the array to fit full weeks
truncated_temperatures = daily_temperatures[:num_weeks * 7]

# Calculate weekly averages
weekly_averages = truncated_temperatures.reshape(-1, 7).mean(axis=1)
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures:
 [34 14 16  2  3 17 22 24 24 23  7 27 20 33 14 10 27 19 22 12 13 27  5 32
 15 26 11 13 19 28]
Weekly Averages:
 [15.42857143 22.57142857 16.71428571 18.42857143]
